name: molres
channels:
  - defaults
  - rdkit
  - conda-forge
dependencies:
  - python=3.7
  - pandas
  - jupyter
  - git
  - rdkit
  - matplotlib
  - scikit-learn
  - requests
  - pip:
    - pytdc==0.3.6
